version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.4.0
    - 1.4.1
    - 1.5.0
    - 1.5.1
    - 1.6.0
    - 1.6.1
    - 1.6.2
  - dependency-name: color-string
    versions:
    - 1.5.5
  - dependency-name: antd
    versions:
    - 4.15.0
    - 4.15.5
    - 4.16.4
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.13.8
    - 7.14.2
    - 7.14.4
    - 7.14.5
    - 7.14.7
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.10
    - 7.13.16
    - 7.13.17
    - 7.14.0
    - 7.14.5
    - 7.14.6
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.10
    - 7.13.15
    - 7.14.2
    - 7.14.3
    - 7.14.5
  - dependency-name: postcss
    versions:
    - 8.2.10
  - dependency-name: ua-parser-js
    versions:
    - 0.7.28
  - dependency-name: webpack
    versions:
    - 5.28.0
    - 5.34.0
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: url-loader
    versions:
    - 4.1.1
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: acorn
    versions:
    - 5.7.4
  - dependency-name: "@babel/plugin-syntax-dynamic-import"
    versions:
    - 7.8.3
  - dependency-name: uglifyjs-webpack-plugin
    versions:
    - 2.2.0
  - dependency-name: css-hot-loader
    versions:
    - 1.4.4
  - dependency-name: autoprefixer
    versions:
    - 9.8.6
