version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.12.18
    - 7.12.5
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.16
    - 7.13.2
    - 7.13.4
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.28.0
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.15
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.2
    - 7.13.4
    - 7.13.5
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.13.0
  - dependency-name: antd
    versions:
    - 3.26.20
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
